Repository AECOFARM/aecofarm-BE, pull requests merged in 2024-07, with the labels that each got.

#2 ✨ [FEAT] 로그인, 회원가입 API 구현
  build.gradle
  src/main/java/dgu/aecofarm/config/WebConfig.java
  src/main/java/dgu/aecofarm/config/auth/JwtTokenFilter.java
  src/main/java/dgu/aecofarm/config/auth/SecurityConfig.java
  src/main/java/dgu/aecofarm/domain/member/controller/MemberController.java
  src/main/java/dgu/aecofarm/domain/member/service/MemberService.java
  src/main/java/dgu/aecofarm/domain/member/service/MemberServiceImpl.java
  src/main/java/dgu/aecofarm/dto/member/FindPasswordRequestDTO.java
  src/main/java/dgu/aecofarm/dto/member/JwtInfoResponseDTO.java
  src/main/java/dgu/aecofarm/dto/member/LoginRequestDTO.java
  src/main/java/dgu/aecofarm/dto/member/LoginResponseDTO.java
  src/main/java/dgu/aecofarm/dto/member/SignupRequestDTO.java
  src/main/java/dgu/aecofarm/entity/Member.java
  src/main/java/dgu/aecofarm/repository/MemberRepository.java
  src/main/java/dgu/aecofarm/util/JwtTokenUtil.java
Labels: :sparkles: feature

#4 ✨ [FEAT] 게시글 등록, 수정, 삭제 구현
  src/main/java/dgu/aecofarm/domain/contract/controller/ContractController.java
  src/main/java/dgu/aecofarm/domain/contract/service/ContractService.java
  src/main/java/dgu/aecofarm/domain/contract/service/ContractServiceImpl.java
  src/main/java/dgu/aecofarm/dto/contract/CreateContractRequestDTO.java
  src/main/java/dgu/aecofarm/entity/Contract.java
  src/main/java/dgu/aecofarm/entity/Item.java
  src/main/java/dgu/aecofarm/exception/GlobalExceptionHandler.java
  src/main/java/dgu/aecofarm/exception/InvalidUserIdException.java
  src/main/java/dgu/aecofarm/repository/ContractRepository.java
  src/main/java/dgu/aecofarm/repository/ItemRepository.java
Labels: :sparkles: feature

#8 ✨ [FEAT] 대여하기 요청 API 구현
  src/main/java/dgu/aecofarm/domain/borrow/controller/BorrowController.java
  src/main/java/dgu/aecofarm/domain/borrow/service/BorrowService.java
  src/main/java/dgu/aecofarm/domain/borrow/service/BorrowServiceImpl.java
  src/main/java/dgu/aecofarm/domain/contract/service/ContractServiceImpl.java
  src/main/java/dgu/aecofarm/domain/member/service/MemberServiceImpl.java
  src/main/java/dgu/aecofarm/dto/contract/ContractDetailResponseDTO.java
  src/main/java/dgu/aecofarm/entity/Alarm.java
  src/main/java/dgu/aecofarm/entity/Contract.java
  src/main/java/dgu/aecofarm/entity/alarmStatus.java
  src/main/java/dgu/aecofarm/repository/AlarmRepository.java
Labels: :sparkles: feature

#12 ✨ [FEAT] 대여하기 승인, 거절 API 구현
  src/main/java/dgu/aecofarm/domain/borrow/controller/BorrowController.java
  src/main/java/dgu/aecofarm/domain/borrow/service/BorrowService.java
  src/main/java/dgu/aecofarm/domain/borrow/service/BorrowServiceImpl.java
  src/main/java/dgu/aecofarm/domain/lend/service/LendServiceImpl.java
  src/main/java/dgu/aecofarm/dto/borrow/AcceptRejectRequestDTO.java
  src/main/java/dgu/aecofarm/entity/Alarm.java
  src/main/java/dgu/aecofarm/entity/AlarmStatus.java
  src/main/java/dgu/aecofarm/entity/Contract.java
  src/main/java/dgu/aecofarm/repository/AlarmRepository.java
Labels: :sparkles: feature

#40 ✨ [REFACTOR] 게시글 상세 조회 API 수정
  src/main/java/dgu/aecofarm/domain/contract/service/ContractServiceImpl.java
  src/main/java/dgu/aecofarm/dto/contract/ContractDetailResponseDTO.java
Labels: :zap: zap

#41 ⚡ [REFACTOR] 마이페이지 내가 쓴 글 조회 API 수정
  src/main/java/dgu/aecofarm/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/dgu/aecofarm/repository/ContractRepository.java
Labels: :zap: zap

#44 ✨ [FEAT] 프로필 사진 S3업로드 API 구현
  build.gradle
  src/main/java/dgu/aecofarm/config/AWSConfig.java
  src/main/java/dgu/aecofarm/domain/member/controller/MemberController.java
  src/main/java/dgu/aecofarm/domain/member/service/MemberService.java
  src/main/java/dgu/aecofarm/domain/member/service/MemberServiceImpl.java
  src/main/java/dgu/aecofarm/dto/member/SignupRequestDTO.java
Labels: :sparkles: feature

#45 🔀 [MERGE] develop branch에서 main branch로 merge
  build.gradle
  src/main/java/dgu/aecofarm/config/AWSConfig.java
  src/main/java/dgu/aecofarm/domain/member/controller/MemberController.java
  src/main/java/dgu/aecofarm/domain/member/service/MemberService.java
  src/main/java/dgu/aecofarm/domain/member/service/MemberServiceImpl.java
  src/main/java/dgu/aecofarm/dto/member/SignupRequestDTO.java
Labels: :twisted_rightwards_arrows: merge

#47 ⚡ [REFACTOR] 마이페이지 프로필 수정 사진 S3연결
  src/main/java/dgu/aecofarm/domain/mypage/controller/MyPageController.java
  src/main/java/dgu/aecofarm/domain/mypage/service/MyPageService.java
  src/main/java/dgu/aecofarm/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/dgu/aecofarm/dto/mypage/UpdateProfileDTO.java
Labels: :zap: zap

#49 ⚡ [REFACTOR] 게시글 등록, 수정 image 받아오기 추가
  src/main/java/dgu/aecofarm/domain/contract/controller/ContractController.java
  src/main/java/dgu/aecofarm/domain/contract/service/ContractService.java
  src/main/java/dgu/aecofarm/domain/contract/service/ContractServiceImpl.java
  src/main/java/dgu/aecofarm/dto/contract/CreateContractRequestDTO.java
Labels: :zap: zap

#50 🔀 [MERGE] main으로 merge
  src/main/java/dgu/aecofarm/domain/contract/service/ContractServiceImpl.java
  src/main/java/dgu/aecofarm/domain/mypage/controller/MyPageController.java
  src/main/java/dgu/aecofarm/domain/mypage/service/MyPageService.java
  src/main/java/dgu/aecofarm/domain/mypage/service/MyPageServiceImpl.java
Labels: :sparkles: feature, :twisted_rightwards_arrows: merge
